version: '3.8'

services:
  implementos-agno-api:
    build: .
    container_name: implementos-agno-api
    ports:
      - "7777:7777"
    volumes:
      - ./.env:/app/.env
      - ./key-storage.json:/app/key-storage.json
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped